# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package Github

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install pnpm -g

      - name: Run test cases
        uses: denoland/setup-deno@v1
      - run: pnpm test

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Github package
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com/
      - run: npm install pnpm -g
      - run: pnpm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
